### ISSUE TITLE
rubyzip not behaving well with YJIT

### ISSUE THREAD

**Issue by flavorjones** [Shopify/yjit#310]
Extracting files from a zip archive with `rubyzip`, when YJIT is enabled I frequently see errors during extraction. I have reproduced this on Ruby 3.2.0 and master (35136e1e9c). I can easily reproduce on `x86_64-linux` but cannot repro on `arm64-darwin`.

Typical error messages have to do with the extracted size or, less often, a zlib error.

Repro:

```ruby
#! /usr/bin/env ruby

puts RUBY_DESCRIPTION

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "rubyzip"
end

require "zip"

number_of_files = 2
file_size       = 1_000_000
alpha           = ('a'..'z').to_a # for generating some random data
line_length     = alpha.length

Dir.mktmpdir("repro-source") do |sourcedir|
  puts "generating source files ..."
  Dir.chdir(sourcedir)
  number_of_files.times do |j|
    file = "#{j}.txt"
    File.open(file, "w") do |f|
      (file_size / line_length).times do
        f.puts alpha.sample(line_length).join
      end
    end
    puts File.read(file).length
  end

  system("zip foo.zip *.txt")
  system("ls -l foo.zip")
  system("unzip -l foo.zip")

  while true
    Zip::File.open(File.expand_path("foo.zip")) do |zipfile|
      Dir.mktmpdir("repro-extract") do |tmpdir|
        Dir.chdir(tmpdir) do
          zipfile.each do |entry|
            puts entry.name
            entry.extract
          end
        end
      end
    end
  end
end
```

Typical output:

```
$ ./ruby --yjit ./repro-rubyzip-issue.rb 
ruby 3.3.0dev (2023-02-26T20:39:41Z master 35136e1e9c) +YJIT [x86_64-linux]
generating source files ...
1038447
1038447
  adding: 0.txt (deflated 36%)
  adding: 1.txt (deflated 36%)
-rw-rw-r-- 1 flavorjones flavorjones 1327884 Feb 26 17:04 foo.zip
Archive:  foo.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  1038447  2023-02-26 17:04   0.txt
  1038447  2023-02-26 17:04   1.txt
---------                     -------
  2076894                     2 files
0.txt
1.txt
0.txt
1.txt
0.txt
1.txt
0.txt
1.txt
0.txt
1.txt
0.txt
1.txt
<snip>
0.txt
1.txt
0.txt
/home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:631:in `block (2 levels) in create_file': entry '0.txt' should be 1038447B, but is larger when inflated. (Zip::EntrySizeError)
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:540:in `get_input_stream'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:621:in `block in create_file'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:620:in `open'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:620:in `create_file'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:187:in `extract'
	from ./repro-rubyzip-issue.rb:42:in `block (5 levels) in <main>'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:38:in `block in each'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37:in `each'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37:in `each'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:185:in `each'
	from ./repro-rubyzip-issue.rb:40:in `block (4 levels) in <main>'
	from ./repro-rubyzip-issue.rb:39:in `chdir'
	from ./repro-rubyzip-issue.rb:39:in `block (3 levels) in <main>'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/3.3.0+0/tmpdir.rb:94:in `mktmpdir'
	from ./repro-rubyzip-issue.rb:38:in `block (2 levels) in <main>'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
	from ./repro-rubyzip-issue.rb:37:in `block in <main>'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/3.3.0+0/tmpdir.rb:94:in `mktmpdir'
	from ./repro-rubyzip-issue.rb:19:in `<main>'
```

**Comment by flavorjones** [comment]
Also, I've noticed that reproducing this is sensitive to the contents of the compressed files. Calling `Random.srand(2)` on my machine reliably reproduces very quickly.

**Comment by maximecb** [comment]
Alan just pushed a bugfix. Could you try running the test again on master and see if it works correctly now?

**Comment by flavorjones** [comment]
@maximecb @XrXr I just tested with `ba55706fb6` and it's still happening:

```
$ ./ruby --yjit ./repro-rubyzip-issue.rb 
ruby 3.3.0dev (2023-02-27T21:34:27Z master ba55706fb6) +YJIT [x86_64-linux]
generating source files ...
1038447
1038447
  adding: 0.txt (deflated 36%)
  adding: 1.txt (deflated 36%)
-rw-rw-r-- 1 flavorjones flavorjones 1327819 Feb 27 16:44 foo.zip
Archive:  foo.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  1038447  2023-02-27 16:44   0.txt
  1038447  2023-02-27 16:44   1.txt
---------                     -------
  2076894                     2 files
0.txt
1.txt
0.txt
/home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:631:in `block (2 levels) in create_file': entry '0.txt' should be 1038447B, but is larger when inflated. (Zip::EntrySizeError)
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:540:in `get_input_stream'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:621:in `block in create_file'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:620:in `open'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:620:in `create_file'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry.rb:187:in `extract'
	from ./repro-rubyzip-issue.rb:43:in `block (5 levels) in <main>'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:38:in `block in each'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37:in `each'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37:in `each'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:185:in `each'
	from ./repro-rubyzip-issue.rb:41:in `block (4 levels) in <main>'
	from ./repro-rubyzip-issue.rb:40:in `chdir'
	from ./repro-rubyzip-issue.rb:40:in `block (3 levels) in <main>'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/3.3.0+0/tmpdir.rb:94:in `mktmpdir'
	from ./repro-rubyzip-issue.rb:39:in `block (2 levels) in <main>'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.3.0+0/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
	from ./repro-rubyzip-issue.rb:38:in `block in <main>'
	from /home/flavorjones/.rbenv/versions/3.3.0-dev/lib/ruby/3.3.0+0/tmpdir.rb:94:in `mktmpdir'
	from ./repro-rubyzip-issue.rb:20:in `<main>'
```

**Comment by casperisfine** [comment]
This could be an old bug, I vaguely remember some ZLib errors being thrown by bundler when YJIT was enabled by in 3.1. I don't remember at all what the conclusion was.

**Comment by netrusov** [comment]
I'm also facing this issue with GeoIP2 archive, but it's not reproducible: I have multiple instances of the same application running on Ruby 3.2.1 (and on 3.2.0 previously) with YJIT enabled, some of them will deflate file without problem, while others will fail. it can finish without issues after retry, so it's very hard to debug

the error is `zlib error while inflating (Zip::DecompressionError)`

**Comment by maximecb** [comment]
The bug should now be fixed.

**Comment by flavorjones** [comment]
Confirming, I can no longer repro the issue using 611a6425. Thanks!
